workspace.members = [
    # === examples ===
    "examples/chatgpt",
    "examples/ironfish",
    "examples/teamtalk",
    "examples/fractal_zoom",
    "examples/simple",
    "examples/ui_zoo",
    "examples/news_feed",
    "examples/web_cam",
    "examples/text_flow",
    "examples/teamtalk",
    "examples/websocket_image",
    "examples/snake",
    "examples/slides",
    "examples/image_viewer/step_1",
    "examples/image_viewer/step_2",
    "examples/image_viewer/step_3",
    "examples/image_viewer/step_4",
    "examples/image_viewer/step_5",
    "examples/image_viewer/step_6",
    "examples/image_viewer/step_7",
    "examples/image_viewer/step_8",
    "examples/image_viewer/step_9",
    "examples/image_viewer/step_10",
    "examples/image_viewer/step_11",
    "examples/image_viewer/step_12",
    "examples/image_viewer/step_13",
    "examples/image_viewer/step_14",
    "examples/image_viewer/step_15",
    "examples/image_viewer/step_16",
    "examples/image_viewer/step_17",
    "studio",
    "tools/cargo_makepad",
    "tools/auto_version",
    # === projects ===
    "projects/test_1",
    # === libs ===
    "libs/array_vec",
    "libs/btree",
    "libs/btree_vec",
    #"experiments/scroll",
    "examples/image_viewer_1",
    "examples/image_viewer_2",
    "examples/image_viewer_3",
    "examples/image_viewer_4",
    "examples/image_viewer_5",
    "examples/image_viewer_6",
]

workspace.exclude = [
    "code_editor",
    "libs/stitch",
    "libs/futures",
    "libs/wasm_bridge/test",
    "tools/windows_strip",
    "tools/web_server",
    "tools/file_router",
    "tools/wasm_strip",
]

workspace.resolver = "2"
#debug = true

[profile.small]
inherits = "release"
#debug = true
opt-level = 'z'   # Optimize for size
lto = true        # Enable link-time optimization
codegen-units = 1 # Reduce number of codegen units to increase optimizations
panic = 'abort'   # Abort on panic
strip = true


#[profile.dev.package.makepad-live-tokenizer]
#opt-level = 3
#[profile.dev.package.makepad-live-compiler]
#opt-level = 3
#[profile.dev.package.makepad-shader-compiler]
#opt-level = 3
#[profile.dev.package.makepad-platform]
#opt-level = 3
#[profile.dev.package.makepad-draw]
#opt-level = 3
#[profile.dev.package.makepad-vector]
#opt-level = 3
#[profile.dev.package.rustybuzz]
#opt-level = 3
#[profile.dev.package.bitflags]
#opt-level = 3
#[profile.dev.package.bytemuck]
#opt-level = 3
#[profile.dev.package.smallvec]
#opt-level = 3
#[profile.dev.package.unicode-bidi-mirroring]
#opt-level = 3
#[profile.dev.package.unicode-ccc]
#opt-level = 3
#[profile.dev.package.unicode-properties]
#opt-level = 3
#[profile.dev.package.unicode-script]
#opt-level = 3
#[profile.dev.package.unicode-bidi]
#opt-level = 3
#[profile.dev.package.ttf-parser]
#opt-level = 3
