[package]
name = "makepad-file-server"
version = "0.5.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad file server"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"
metadata.makepad-auto-version = "K1ZQL60Gs8fF9js94ms2TAZwPKQ="

[dependencies]
makepad-shell = {path="../../libs/shell" , version="0.4.0"}
makepad-live-id = { path = "../../libs/live_id", version = "0.4.0"}
makepad-micro-serde = {path = "../../libs/micro_serde", version = "0.4.0"}
makepad-file-protocol = {path="../file_protocol", version="0.5.0"}
makepad-rabin-karp = {path="../../libs/rabin-karp",version="0.1.0"}